apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-model
  namespace: default
spec:
  replicas: 2  # This starts 2 pods across your laptops
  selector:
    matchLabels:
      app: titanic
  template:
    metadata:
      labels:
        app: titanic
    spec:
      containers:
      - name: titanic-container
        image: abajpai8/titanic-predictor:v4
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: titanic-service
  namespace: default
spec:
  selector:
    app: titanic
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer # This creates the "Front Door"